source(paste0(function.dir,"rawDataFormatting.R"))
source(paste0(function.dir,'km.R'))
source(paste0(function.dir,'generateFigure.R'))
source(paste0(function.dir,'generateTable.R'))
source(paste0(function.dir,'designFigure.R'))

if(is.null(config)){stop('No configuration found. Please check...')}

##### Beginning of Pipeline #####

# format data
# this is a weak/brittle check for single vs. multi-mouse experiments
# if "pdx_id" is present, then it's probably single-mouse

if ("pdx_id" %in% colnames(x)) {
  dat <- format.all.single.mouse.data(x)
  single.mouse <- TRUE
} else {
  dat <- format.all.data(x)  
  single.mouse <- FALSE  
}





if(exists("w")){
  dat <- format.all.weight(dat, w)
}

# fit Kaplan-Meier
dat$km <- km_fit(dat$formattedData[!dat$formattedData$exclude, ])

# weight plot 
if (single.mouse == FALSE) {
  suppressWarnings({
    dat$weight.plot <- weight.plot(dat, color = config$weight.color,
                                   font.factor = config$font.factor,
                                   line.factor = config$line.factor,
                                   config = config)
  })  
}


# survival plot
if (single.mouse == FALSE) {
  suppressWarnings({
     dat$survival.plot <- survival.plot(dat, color = config$km.color,
                                        censored = sum(dat$formattedData[!dat$formattedData$exclude, ]$survival.event == 0) > 0,
                                        font.factor = config$font.factor,
                                        line.factor = config$line.factor,
                                        config = config)
    #dat$survival.plot <- survival.plot.kathryn(dat, color = config$km.color,
    #                                           censored = sum(dat$formattedData[!dat$formattedData$exclude, ]$survival.event == 0) > 0,
    #                                           font.factor = config$font.factor,
    #                                           line.factor = config$line.factor)
  })  
}


# %cd45 plot
if (single.mouse == FALSE) {
  suppressWarnings({
    dat$cd45.median <- calc.median(dat, "cd45")
    dat$cd45.plot <- volume.rtv.cd45.plot(dat,"cd45", color = config$cd45.color,
                                          font.factor = config$font.factor,
                                          line.factor = config$line.factor)
    # dat$cd45.plot <- volume.rtv.cd45.plot.kathryn(dat,"cd45", color = config$cd45.color,
    #                                               font.factor = config$font.factor,
    #                                               line.factor = config$line.factor)
  })  
} else if (single.mouse == TRUE) {
  suppressWarnings({
    
    dat$cd45.plot <- volume.rtv.cd45.single.mouse.plot(dat, "cd45",
                                                     font.factor = config$font.factor,
                                                     line.factor = config$line.factor)
  })
}

#swimmer plot
if (single.mouse == TRUE) {
  dat$swimmer.plot <- swimmer.plot.single.mouse(dat)

}





# perform exact log rank test
if (single.mouse == FALSE) {
  dat$exact_rank_tests <- list()
  for (test in config$table.comparisons){
    dat$exact_rank_tests[[paste(test[1], test[2], sep=" vs ")]] <-
      exact_rank_test(dat$formattedData[!dat$formattedData$exclude, ], groupconf = test)
  }
  
  # perform Gehan-Wilcoxon test
  dat$wilcoxon_tests <- list()
  for (test in config$table.comparisons){
    dat$wilcoxon_tests[[paste(test[1], test[2], sep=" vs ")]] <-
      wilcoxon_test(dat$formattedData[!dat$formattedData$exclude, ], groupconf = test)
  }
  
}


# format tables
if (single.mouse == FALSE) {
  suppressWarnings({
    dat$table <- format.ALL.table(dat, config) #original summary.xlsx table - human readable format
  })  
  suppressWarnings({
    dat$table2 <- format.ALL.table2(dat, config) #Jan2021 summary.csv - more details on drug, dose, schedule, cancer type, etc., and flat file
  })
} else if (single.mouse == TRUE) {
  suppressWarnings({
    dat$table <- format.ALL.single.mouse.table(dat,config)
  })
}






#waterfall plot
#relies on dat$table which is generated by format.ALL.table above
if (single.mouse == TRUE) {
  dat$waterfall.plot <- waterfall.plot.single.mouse(dat)
} else {
  # not developed yet
}



